config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Hours::Application.routes.draw do
  constraints(SubdomainPresent) do
    root "projects#index", as: :subdomain_root
    devise_for :users, :controllers => { registrations: "users/registrations" }
    resources :projects, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :create]
    resources :entries, only: [:create, :destroy, :update, :edit]
    resources :users, only: [] do
      resources :entries, only: :index
    end
  end

  constraints(SubdomainBlank) do
    root to: "pages#show", id: "landing"
    get "/pages/*id" => "pages#show", as: :page, format: false

    resource :accounts, only: [:new, :create]
  end
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id          :integer          not null, primary key
#  project_id  :integer          not null
#  category_id :integer          not null
#  user_id     :integer          not null
#  hours       :integer          not null
#  date        :date             not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Entry < ActiveRecord::Base
  belongs_to :project, touch: true
  belongs_to :category
  belongs_to :user, touch: true
  has_many :taggings, inverse_of: :entry
  has_many :tags, through: :taggings

  validates :user, presence: true
  validates :project, presence: true
  validates :category, presence: true
  validates :hours, presence: true,
                    numericality: { greater_than: 0 }
  validates :date, presence: true
  accepts_nested_attributes_for :taggings

  scope :by_last_created_at, -> { order("created_at desc") }
  scope :by_date, -> { order("date DESC") }

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where("name ILIKE ?", n.strip).first_or_initialize.tap do |tag|
        tag.name = n.strip
        tag.save!
      end
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  DATE_FORMAT = "%d/%m/%Y"

  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user
    if @entry.save
      redirect_to root_path, notice: t(:entry_created)
    else
      redirect_to root_path, notice: @entry.errors.full_messages.join(" ")
    end
  end

  def index
    @user = User.find_by_slug(params[:user_id])
    @entries = @user.entries.by_date.page(params[:page]).per(10)
  end

  def update
    @entry = entry
    @entry.update_attributes(entry_params)
    if entry.save
      redirect_to user_entries_path(current_user), notice: t("entry_saved")
    else
      render "edit", notice: t("entry_failed")
    end
  end

  def edit
    @entry = entry
  end


  def destroy
    @entry = entry
    @entry.destroy
    redirect_to user_entries_path(current_user), notice: t('entry_deleted')
  end

  private

  def entry_params
    params.require(:entry)
      .permit(:project_id, :category_id, :hours, :tag_list, :date)
      .merge(date: parsed_date)
  end

  def parsed_date
    Date.strptime(params[:entry][:date], DATE_FORMAT)
  end

  def entry
    current_user.entries.find(params[:id])
  end
end

app/views/entries/edit.html.erb
<div class="outer">
  <div class="wrapper">
    <div class="projects-overview">
      <%= render partial: "application/entry_form", locals: { form_title: t("entries.index.edit_entry") } %>
    </div>
  </div>
</div>

app/views/entries/index.html.erb
<% cache @user do %>
  <div class="outer">
    <div class="container">
      <h1><%= t('entries.index.user_hours', user: @user.first_name) %></h1>
      <div class="hours-per-project-overview">
        <canvas id="hours-per-project" data-data="<%= @user.hours_per_project.to_json %>" width=200 height=200 ></canvas>
        <div class="spent-info">
          <span class="hours" style="color: #D66278"><%= @user.hours_spent %></span>
        </div>
      </div>
      <ul class="legend">
        <% @user.projects.each do |project| %>
          <li>
          <span class="color" style="background-color: <%= project.name.pastel_color %>"></span> <%= project.name %>: <%= @user.percentage_spent_on(project).round %>% (<%= @user.hours_spent_on(project) %><%= t('entries.index.hours_indication') %>)
          </li>
        <% end %>
        <li><strong><%= t('entries.index.total', hours_spent: @user.hours_spent) %><%= t('entries.index.hours_indication') %></strong></li>
      </ul>
      <table class="entries">
        <thead>
          <tr>
            <th><%= t("entries.index.date") %></th>
            <th><%= t("entries.index.project") %></th>
            <th class="center"><%= t("entries.index.hours") %></th>
            <th class="hide-for-mobile"><%= t("entries.index.category") %></th>
            <th class="hide-for-mobile"><%= t("entries.index.tags") %></th>
            <% if @user == current_user %>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
        <% @entries.each do |entry| %>
          <% cache entry do %>
            <tr class="info-row">
              <td><%= l(entry.date) %></td>
              <td><%= link_to entry.project.name, entry.project %></td>
              <td class="center"><%= entry.hours %></td>
              <td class="hide-for-mobile">
                <div class="project">
                  <span class="color" style="background-color:<%= entry.category.name.pastel_color %>;"></span>
                  <span><%= entry.category.name %></span>
                </div>
              </td>
              <td class="hide-for-mobile">
                <div class="table-tags">
                  <%= entry.tag_list %>
                </div>
              </td>
              <% if @user == current_user %>
                <td class="right">
                  <%= link_to t('entries.index.edit'), edit_entry_path(entry) %> |
                  <%= link_to t('entries.index.delete'), entry, method: :delete, class: "destroy", data: { confirm: t(:confirm) } %>
                </td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= paginate @entries %>
    </div>
  </div>
<% end %>