config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Hours::Application.routes.draw do
  constraints(SubdomainPresent) do
    root "projects#index", as: :subdomain_root
    devise_for :users, :controllers => { registrations: "users/registrations" }
    resources :projects, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :create]
    resources :entries, only: [:create, :destroy, :update, :edit]
    resources :users, only: [] do
      resources :entries, only: :index
    end
  end

  constraints(SubdomainBlank) do
    root to: "pages#show", id: "landing"
    get "/pages/*id" => "pages#show", as: :page, format: false

    resource :accounts, only: [:new, :create]
  end
end

app/views/pages/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <ul>
      <li>
        <%= link_to root_path do %>
          <h3>Hours</h3>
        <% end %>
      </li>
      <li><a href="<%= root_path %>#pricing">Pricing</a></li>
      <li><%= link_to "The Team", page_path("team") %></li>
      <li><a href="mailto:hugo@defacto.nl">Careers</a></li>
    </ul>
  </div>
  <hr>
  <p>Greetings from drizzling <a href="https://www.flickr.com/search/?q=groningen">Groningen.</a> <br> - The Hours team.</p>
</footer>

app/views/pages/landing.html.erb
<% cache static_cache_key_for(:landing) do %>
  <div class="hero">
    <div class="hero-inner">
      <div class="hero-copy">
        <h1 id="logo">
          <%= image_tag("logo-white-shadow.png", alt: 'Hours') %>
        </h1>
        <h2>Time registration that doesn't suck.</h2>
        <%= link_to new_accounts_path, class: "button" do %>
          <div class="flip">
            <div class="flip-front"><span>Free<br>Trial</span></div>
            <div class="flip-back"><span>Free<br>Trial</span></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="main">
    <div class="copy">
      <p>Hours is a dead simple project based time tracking application that <%= link_to "we", page_path("team") %> use for internal time-tracking. It allows users to register how many hours they've worked on a project with a certain category (think design, software development, testing for software teams) and add any tag they like to it. This gives us a lot of insight on how we spend our time on different projects.</p>
    </div>
  </div>

  <div class="browsers">
    <div class="browser">
      <div class="browser-top-bar">
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
      </div>
    <div class="browser-content"></div>
    </div>
    <div class="browser">
      <div class="browser-top-bar">
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
      </div>
      <div class="browser-content">
      </div>
    </div>
    <div class="browser">
      <div class="browser-top-bar">
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
        <div class="browser-circle"></div>
      </div>
      <div class="browser-content"></div>
    </div>
  </div>

  <div class="pricing" id="pricing">
    <h1>Pricing</h1>
    <div class="cards">
        <div class="card">
          <%= link_to new_accounts_path do %>
            <div class="card-image free">
            <p>Freelance</p>
            </div>
          <% end %>
          <div class="card-header">
            Free!
          </div>
          <div class="card-copy">
            <p><strong>Hours</strong> is free for small teams and freelancers: if you are up to 5 people, this one's on us! </p>
          </div>
          <div class="card-stats">
            <ul>
              <li>5<span>Users</span></li>
              <li>Unlimited<span>Projects &amp; Entries</span></li>
            </ul>
          </div>
        </div>

      <div class="card">
        <div class="ribbon-wrapper"><div class="ribbon">Popular</div></div>
        <%= link_to new_accounts_path do %>
          <div class="card-image medium">
            <p>Small Teams</p>
          </div>
        <% end %>
        <div class="card-header">
          $25 / month
        </div>
        <div class="card-copy">
          <p>Tailored toward consultancies and medium sized teams, this plan will only cost you less than a beer per user per month. If you can't afford us, stop drinking so much beer!</p>
        </div>
        <div class="card-stats">
          <ul>
            <li>25<span>Users</span></li>
            <li>Unlimited<span>Projects &amp; entries</span></li>
          </ul>
        </div>
      </div>

      <div class="card">
        <%= link_to new_accounts_path do %>
          <div class="card-image enterprise">
            <p>Enterprise</p>
          </div>
        <% end %>
        <div class="card-header">
          Call us :)
        </div>
        <div class="card-copy">
          <p><a href="tel:+31 50 3144832">Call us,</a> maybe... </p>
          <p><strong>+31 50 314 48 32</strong></p>
        </div>
        <div class="card-stats">
          <ul>
            <li>25+<span>Users</span></li>
            <li>Unlimited<span>everything</span></li>
          </ul>
        </div>
      </div>
    </div>

    <p>Or start with a <strong>free</strong> trial. No credit card needed.</p>
    <%= link_to new_accounts_path do %>
      <button>Free trial</button>
    <% end %>

    <p><small>Alternatively you can grab the <a href="https://github.com/DefactoSoftware/Hours/">source</a> from Github and host it yourself.</small><p>
  </div>
  <%= render "footer" %>
<% end %>

app/views/pages/team.html.erb
<% cache static_cache_key_for(:team) do %>
  <div class="hero team-header">
    <div class="hero-inner">
      <div class="hero-copy">
        <%= link_to root_path do %>
          <h1 id="logo">
            <%= image_tag("logo-white-shadow.png", alt: 'Hours') %>
          </h1>
        <% end %>
        <h2>The Team</h2>
      </div>
    </div>
  </div>

  <div class="main">
    <div class="copy">
      <ul class="team">
        <li>
          <a href="https://github.com/jurre">
            <%= image_tag("jurre.jpg") %>
            <p>Jurre Stender</p>
          </a>
        </li>
        <li>
          <a href="https://github.com/dkhgh">
            <%= image_tag("hugo.jpg") %>
            <p>Hugo Veeger</p>
          </a>
        </li>
        <li>
          <a href="https://github.com/sn3p">
            <%= image_tag("matthijs.jpg") %>
            <p>Matthijs Kuiper</p>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <%= render "footer" %>
<% end %>