config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Hours::Application.routes.draw do
  constraints(SubdomainPresent) do
    root "projects#index", as: :subdomain_root
    devise_for :users, :controllers => { registrations: "users/registrations" }
    resources :projects, only: [:index, :new, :create, :show]
    resources :categories, only: [:index, :create]
    resources :entries, only: [:create, :destroy, :update, :edit]
    resources :users, only: [] do
      resources :entries, only: :index
    end
  end

  constraints(SubdomainBlank) do
    root to: "pages#show", id: "landing"
    get "/pages/*id" => "pages#show", as: :page, format: false

    resource :accounts, only: [:new, :create]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_schema, :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_locale

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    klass.new(object, view_context)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email,
               :password, :password_confirmation)
    end
  end

  private

  def current_account
    @current_account ||= Account.find_by(subdomain: request.subdomain)
  end

  helper_method def current_subdomain
    @current_subdomain ||= current_account.subdomain
  end

  def load_schema
    Apartment::Tenant.switch("public")
    return unless request.subdomain.present?

    if current_account
      Apartment::Tenant.switch(request.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def after_sign_out_path(resource_or_scope)
    new_user_session_path
  end

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_path(link_text, link_path, http_method=nil)
    css_class = "navigation"
    css_class << " current" if current_page?(link_path)
    content_tag :li, class: css_class do
      link_to(link_text, link_path, http_method)
    end
  end

  def user_image_link(user, opts={}, &block)
    link_to user_entries_path(user) do
      if opts[:border]
        concat gravatar_image_tag user.email, gravatar: { secure: true }, class: "image-circle", title: user.full_name, style: "border: 3px solid #{user.full_name.pastel_color}"
      else
        concat gravatar_image_tag user.email, gravatar: { secure: true }, class: "image-circle", title: user.full_name
      end
      concat yield if block_given?
    end
  end

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end
end

app/views/application/_entry.html.erb
<% cache entry do %>
  <li>
    <div clas="entry">
      <div class="avatar-container">
        <div class="avatar">
          <%= user_image_link(entry.user) %>
        </div>
      </div>
      <div class="entry-text">
        <%= t(:entry_activity_html,
              user: "<a href='#{user_entries_path(entry.user)}'>#{entry.user.first_name}</a>".html_safe,
              count: entry.hours,
              category: "<span style='font-weight: bold; color:#{entry.category.name.pastel_color} '>#{entry.category.name}</span>".html_safe,
              project: "<a href='#{project_path(entry.project)}'>#{entry.project.name}</a>".html_safe ) %>
            <span class="timestamp" data-timestamp="<%= entry.date %>"><%= l entry.date %></span>
      </div>
    </div>
  </li>
<% end %>

app/views/application/_entry_form.html.erb
<div class="new_entry_wrapper">
  <h2><%= form_title %></h1>
  <%= simple_form_for(@entry) do |f| %>
  <%= f.error_notification %>
      <%= f.association :project, required: true, collection: Project.by_name, label: false, placeholder: t("entries.index.project") %>
      <%= f.association :category, required: true, collection: Category.by_name, label: false, placeholder: t("entries.index.category") %>
      <%= f.input :hours, required: true, label: false, placeholder: t("entries.index.hours") %>
      <%= f.input :date, required: true, as: :string, input_html: { value: (@entry.date || Date.today).strftime("%d/%m/%Y"), id: "datepicker"}, label: false %>
      <%= f.input :tag_list, input_html: { data: { data: Tag.list } }, label: false, placeholder: t("entries.index.tags") %>
      <%= f.button :submit %>
  <% end %>
</div>

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_modal.html.erb
<div class="modal-window">
  <form action="<%= Hours.helpful_url %>" method="post" target="_b">
    <div class="modal-inner">
      <div class="content">
        <label class="modal-close" for="modal-1"></label>
        <h3><%= t('helpful.heading') %></h3>
        <p><%= t('helpful.tagline') %></p>
        <input type="hidden" name="account" value="<%= Hours.helpful_account %>">
        <input type="hidden" id="email" name="email" value="<%= current_user.email %>">
        <textarea id="content" name="content" type="text" placeholder="<%= t('helpful.placeholder') %>"></textarea>
      </div>
        <div class="actions">
          <input type="submit" class="submit-button" value="Submit">
        </div>
    </div>
  </form>z
</div>

app/views/application/_navbar.html.erb
<div id="navbar">
  <div class="nav">
    <ul>
      <%= nav_path t("titles.projects.index"), root_path %>
      <%= nav_path t("titles.entries.index"), user_entries_path(current_user) %>
    </ul>
  </div>

  <% cache current_user do %>
    <div class="nav-user">
      <ul>
        <li id="user-nav" class="dropdown">
          <a href="javascript:void(0)"><%= current_user.first_name %><span class="caret"></span></a>
          <div class="dropdown-menu">
            <div class="dropdown-arrow"></div>
            <div class="dropdown-content">
              <div class="user-info">
                <%= gravatar_image_tag(current_user.email, gravatar: { secure: true }, class: "avatar") %>
                <span class="user-name"><%= current_user.first_name %></span>
              </div>
              <ul>
                <li>
                  <%= link_to t("titles.categories.index"), categories_path %>
                </li>
                <li>
                  <%= link_to t("navbar.dropdown.edit_user"), edit_user_registration_path %>
                </li>
                <% if Hours.helpful_enabled? %>
                  <li >
                    <div class="modal">
                      <label for="modal-1"><a>Help me!</a></label>
                      <input class="modal-state" id="modal-1" type="checkbox">
                      <%= render 'modal' %>
                    </div>
                  </li>
                <% end %>
                <li class="devider"></li>
                <li>
                  <%= link_to t("sign_out"), destroy_user_session_path %>
                </li>
              </ul>
            </div>
          </div>
        </li>
      </ul>
    </div>
<% end %>
</div>